### ISSUE TITLE
Alienware 15 R3 Touchpad Light not working

### ISSUE THREAD

**Issue by bhavsec** [trackmastersteve/alienfx#58]
Everything is working fine except touchpad lights.

- Project Version: alienfx-gtk (2.3.4)
- Operating System: Parrot GNU/Linux 4.5
- Hardware Version: Alienware 15 R3

**Comment by yugioh2017** [comment]
Here too(Alienware 15 R2), any fix?

**Comment by yugioh2017** [comment]
I have fixed the issue if you still interested @bhavsec

**Comment by knicklux** [comment]
@yugioh2017 I would be very interested. Got a cloned repo up and running for the 15r2 and the touchpad seems to be no trivial fix.

**Comment by yugioh2017** [comment]
> @yugioh2017 I would be very interested. Got a cloned repo up and running for the 15r2 and the touchpad seems to be no trivial fix.

Replace this in the alienfx/core/ folder and do rebuild 

https://uptobox.com/bt99ysou0gaf

**Comment by MetalfaceScout** [comment]
Any chance this fix still exists somewhere? Link is a 404 these days.
